project:
  type: website
  output-dir: docs

website:
  title: "Macroeconomic Forecasting"
  sidebar:
    background: primary
    logo: "images/forecasting-logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/zahedasghar/
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: materials.qmd
        text: Materials
      - href: https://discord.com/channels/1208013710463864842/1208013711051194409
        text: Forum

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

